### PR TITLE
revise the desc problem #105

### PR DESCRIPTION
**Pull request by kepper**
here's another shot at the desc problem – thanks for pointing that problem out, @rettinghaus. It seems to work for me, but could you please check?

### CODE REVIEW

**Comment by kepper** [comment]
thanks for having a look :-)

**Comment by rettinghaus** [comment]
@kepper It should work, but Jekyll won't run locally. I get
> Error:  Could not locate the included file 'v4/desc/mei.txt' in any of ["/home/rettinghaus/git/mei-guidelines/_includes", "/var/lib/gems/2.5.0/gems/jekyll-theme-primer-0.5.3/_includes"].

@bwbohl could you try? Or am I missing something?

**Comment by rettinghaus** [comment]
@kepper I still get

> Liquid Exception: Could not locate the included file 'v4/desc/mei.txt' in any of ["/home/rettinghaus/git/mei-guidelines/_includes", "/var/lib/gems/2.5.0/gems/jekyll-theme-primer-0.5.3/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in /home/rettinghaus/git/mei-guidelines/_guidelines-v4/02-shared/01-sharedstructuralelements/01-shareddocumentelements.md

**Comment by rettinghaus** [comment]
everything's fine now

**Comment by kepper** [comment]
what happened? Did't you report that it's still broken two hours ago?

**Comment by rettinghaus** [comment]
@kepper yes, but I figured that my local version of desc-item was somehow different from the upstream version. Fixed that.

**Pull request merged**
