### PR TITLE
Stem sameas docu

### PR DESCRIPTION
**Pull request by frakel**
Adding some lines to distinguish @stem.with from @stem.sameas as requested for PR music-encoding/music-encoding#586

### CODE REVIEW

**Comment by frakel** [comment]
> 
> 
> minor typo (scanario instead of scenario) which can be fixed downstream

this has been already fixed in a5570fec55b6131fbfb64ddc8c34460943ca503e

**Comment by musicEnfanthen** [comment]
@kepper since you approved already, can this PR be merged?

**Comment by bwbohl** [comment]
@kepper considering the dev status of the guidelines, is it safe, to merge this Pr and the corresponding feature at https://github.com/music-encoding/music-encoding/pull/586

**Comment by kepper** [comment]
the proposed changes have been included in https://github.com/music-encoding/guidelines/commit/dfc4dbe6cf92a5cfb1cdce64089ca8bc3cb1e4dd, to circumvent the conflicting files. Thanks @frakel for your work on this!

**Pull request closed without merging**
