### PR TITLE
WIP: Update neume module documentation

### PR DESCRIPTION
**Pull request by vigliensoni**
Add ```neume``` and  ```syl``` elements to documentation. 
Update example.

### CODE REVIEW

**Comment by ahankinson** [comment]
Is this an ongoing WIP, or ready to be merged?

**Comment by vigliensoni** [comment]
I was looking for current documentation and stumbled upon these errors.

This is ready to be merged but will also be updated in the near future.

**Comment by fujinaga** [comment]
Which documentation were you looking at? <neume> etc. are new in Version 4 and were not in Version 3.

On Jun 8, 2018, at 12:10, Gabriel Vigliensoni <notifications@github.com<mailto:notifications@github.com>> wrote:

I was looking for current documentation and stumbled upon these errors.

This is ready to be merged but will also be updated in the near future.

**Comment by vigliensoni** [comment]
I was looking for documentation about neumes and found this in dev (and not
V3):

http://music-encoding.org/guidelines/dev/content/neumes.html

I am just updating the documentation and providing an example that uses the
same elements that are described on the page.

**Comment by vigliensoni** [comment]
@fujinaga Are these specification and example not correct? I would prefer having centralized information that scattered across emails and files.

**Comment by pe-ro** [comment]
The work on the neumes module is in progress.  Once the work is (reasonably) complete, we can look at updating the Guidelines.

**Comment by ahankinson** [comment]
Actually, I think it's OK to keep this PR open, and it just gets updated as things get solidified. We don't need to do it all in one go.

**Comment by ahankinson** [comment]
I just didn't know if it was ready to merge, or if more was going to be added. I've changed the title to reflect the 'work-in-progress' status.

**Comment by bwbohl** [comment]
Just browsing stumbled over the changes introduced to the neumes-sample169.xml file; it has unwanted whitespaces in the attribute declarations, e.g. between `oct=` and `"3"` or `pname` and `"e"` in the following snippet

```xml
<nc tilt="n" oct= "3" pname= "e"/>
```

**Comment by ahankinson** [comment]
Merged as part of the MEI 4.0 release. Further updates may be made separately.

Thanks @vigliensoni !

**Pull request merged**
