### PR TITLE
Chapter 05: correct misleading information

### PR DESCRIPTION
**Pull request by martha-thomae**
Correct misleading information about mensuration and proportion encoding:
- Attributes for encoding **mensuration** in `<staffDef>` were wrong (they were the attributes corresponding to `<mensur>`). Clarified which attributes applied to `<staffDef>` and which ones applied to `<mensur>`
- Attributes for encoding **proportions** in `<staffDef>` were wrong (they were the attributes corresponding to `<proport>`). Clarified which attributes applied to `<staffDef>` and which ones applied to `<proport>`

Added missing information about `@notationtype` (attribute that has been available for a long time, and no documentation of this was given in the mensural chapter).

Finally, removed "5.1 Introduction" section because there was a preamble section. Because of this, all sections have been moved up, and it is easier to see the individual changes (listed above) by checking each commit.

### CODE REVIEW

**Comment by lpugin** [comment]
One question regarding `@num` and `@numbase`: my understanding would be that `staffDef@proport.num` corresponds to `proport@num`. In order for things to be complete, it seems to me that we should also have `staffDef@mensur.num` (and `numbase`) corresponding to `mensur@num`. This would avoid people to encode in `staffDef@proport.num` something to be mapped to `mensur@num` in other encodings. Any thoughts? (Obviously not only an issue for the guidelines but also for the schema)

**Comment by martha-thomae** [comment]
> One question regarding `@num` and `@numbase`: my understanding would be that `staffDef@proport.num` corresponds to `proport@num`. 

Yes, that is correct.

> In order for things to be complete, it seems to me that we should also have `staffDef@mensur.num` (and `numbase`) corresponding to `mensur@num`. This would avoid people to encode in `staffDef@proport.num` something to be mapped to `mensur@num` in other encodings. Any thoughts? (Obviously not only an issue for the guidelines but also for the schema)

I agree, this would make it complete. And, moreover, this might actually be useful for distinguishing the use of proportions for indicating mensuration changes vs. tempo changes (we can use `@mensur.num` and `@mensur.numbase` for the former, while using `@proport.num` and `@proport.numbase` for the latter). Regarldless of this, I agree that for completeness, these things should be added on the schema (for the next version) and I will add the appropriate documentation for that (also in the guidelines of the development branch).

**Comment by martha-thomae** [comment]
Besides the previous point, @lpugin, do you think that this PR is ready for approval and merge?

I just want the guidelines to actually show what is valid on the current version of MEI, and the use of `@num` and `@numbase` in `<staffDef>` is actually not valid. The guidelines were misleading people into using these attributes within `<staffDef>`, rather than the valid attributes `@proport.num` and `@proport.numbase`. So I wanted to clarify this on the current version of the guidelines because it was actually misleading when I presented this on a workshop to people that were just learning how to encode early music using MEI.

**Comment by martha-thomae** [comment]
@lpugin? @kepper?

**Pull request merged**
