### PR TITLE
adding source files for example images 

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR adds all the source MEI files that I used to create the new/changed example images in the Guidelines. 
There is script in there as well, that renders all examples with LilyPond and puts the png into the ExampleImages folder. 

I added the examples to the dev version as well, without the script/xslt, as we probably want to have another approach there when moving the guidelines back to odd.

### CODE REVIEW

**Review by kepper — COMMENTED** [review]
I think this is very useful. However, I'm inclined to not merge it right now, but instead reconsider this in the light of the new setup of the specs and guidelines being merged into one repo. Let's put this on hold for a little time, and see where the best place for this material is…

**Comment by rettinghaus** [comment]
@kepper I'm ok with waiting, but as described above, for the development version there are only the source files in for now, so we can see how we integrate them in the new build process, whereas I think we will keep older versions of the guidelines basically static.

**Comment by rettinghaus** [comment]
As discussed on ODD meeting the script has been moved to the tools folder and a README has been added.

**Review by kepper — APPROVED** [review]
Thanks for taking care of this, @rettinghaus 👍

**Pull request merged**
