### PR TITLE
Rename files

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR simply renames all example files (in the development version) from XML to MEI.

### CODE REVIEW

**Comment by rettinghaus** [comment]
addresses #38

**Comment by ahankinson** [comment]
Did you check that it works by running Jekyll locally?

**Comment by rettinghaus** [comment]
Yes, did this.

Andrew Hankinson <notifications@github.com> schrieb am Do., 21. Juni 2018,
22:08:

**Comment by lpugin** [comment]
I would rather suggest to use .txt instead of .xml or .mei because some of the files are neither mei or xml

**Comment by rettinghaus** [comment]
@lpugin ?!? Why do you say this? Because the XML declaration is missing? They're well formed xml snippets that consist of MEI elements.

**Comment by lpugin** [comment]
See https://github.com/music-encoding/guidelines/blob/07501b123480dd0a5f621b885eb6b6dd9e5b7167/_includes/dev/examples/ptrref/ptrref-sample312.xml

**Comment by rettinghaus** [comment]
Ok, that one's not well formed. I would still go with ".mei". To make these ones valid xml I propose to container the pointers in a more a less generic mei element, like `<label>` or `<ref>`. 
That would be step B after merge.

**Comment by rettinghaus** [comment]
I think it would be wise to have all examples valid MEI.

**Comment by kepper** [comment]
No, it should be possible to exemplify bad use in the Guidelines. Not sure if this is true anymore, but in a former iteration, we had CSS to highlight if an example was valid or not. I would also not wrap the pointers from Laurent's example in an extra element, because that's not relevant in that context, and will almost certainly confuse *some* people. 

A drawback of renaming everything to .mei is that most uninitiated operating systems don't know what to do with those files, while they easily open up XML files. That might not be relevant for people looking up the MEI website repo, though, so you certainly considered that argument already.

**Comment by lpugin** [comment]
Other opinions?

**Comment by ahankinson** [comment]
If they're not valid MEI, I wouldn't call them MEI. But by that same token they're not valid XML either, so they shouldn't be called 'XML'. I'm with @kepper too -- they're not meant to be MEI files, they're meant to be example content.

So renaming them sounds like a good idea, and '.txt' sounds like as good an option as any.

**Comment by rettinghaus** [comment]
I'll take another shot.

**Comment by bwbohl** [comment]
I think this should be postponed until the work on the Guidelines for MEI v4.0.1 is finished

**Pull request closed without merging**
